// Code generated by "stringer -type=Direction,TruncationStrategy,PaddingStrategy,OffsetsCharMode -output=types_string.go ."; DO NOT EDIT.

package tokenizers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Left-0]
	_ = x[Right-1]
}

const _Direction_name = "LeftRight"

var _Direction_index = [...]uint8{0, 4, 9}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TruncateLongestFirst-0]
	_ = x[TruncateOnlyFirst-1]
	_ = x[TruncateOnlySecond-2]
}

const _TruncationStrategy_name = "TruncateLongestFirstTruncateOnlyFirstTruncateOnlySecond"

var _TruncationStrategy_index = [...]uint8{0, 20, 37, 55}

func (i TruncationStrategy) String() string {
	if i >= TruncationStrategy(len(_TruncationStrategy_index)-1) {
		return "TruncationStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TruncationStrategy_name[_TruncationStrategy_index[i]:_TruncationStrategy_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PadLongest-0]
	_ = x[PadFixed-1]
}

const _PaddingStrategy_name = "PadLongestPadFixed"

var _PaddingStrategy_index = [...]uint8{0, 10, 18}

func (i PaddingStrategy) String() string {
	if i >= PaddingStrategy(len(_PaddingStrategy_index)-1) {
		return "PaddingStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PaddingStrategy_name[_PaddingStrategy_index[i]:_PaddingStrategy_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OffsetsCharModeByte-0]
	_ = x[OffsetsCharModeUnicode-1]
}

const _OffsetsCharMode_name = "OffsetsCharModeByteOffsetsCharModeUnicode"

var _OffsetsCharMode_index = [...]uint8{0, 19, 41}

func (i OffsetsCharMode) String() string {
	if i >= OffsetsCharMode(len(_OffsetsCharMode_index)-1) {
		return "OffsetsCharMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OffsetsCharMode_name[_OffsetsCharMode_index[i]:_OffsetsCharMode_index[i+1]]
}
